version: '3.4'

services:
  trelloweb:
    image: trelloweb
    build:
      context: trello-web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
