version: '3.4'

services:
  trelloweb:
    image: trelloweb
    build:
      context: trello-web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
